(()=>{
const WA="919392417891";
const I={bread:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",croissant:"https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80",savory:"https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=800&q=80",pastry:"https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=800&q=80",donut:"https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=800&q=80",cookie:"https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80",cake:"https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",dessert:"https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=800&q=80"};
const raw=[
["BK101","Classic White Bread","breads",55,I.bread,"Soft everyday sandwich loaf with a tender crumb.",["400 g","Eggless","Fresh loaf"]],["BK102","Whole Wheat Brown Bread","breads",70,I.bread,"Nutty whole-wheat loaf for toast and sandwiches.",["400 g","High fibre","Eggless"]],["BK103","Seeded Multigrain Loaf","breads",110,I.bread,"Hearty loaf with oats, flax, sunflower and sesame seeds.",["400 g","5 grains","Eggless"]],["BK104","Country Sourdough","breads",220,I.bread,"Naturally fermented crusty loaf with a mild tang.",["500 g","24-hour ferment","Vegan"]],["BK105","French Baguette","breads",120,I.bread,"Crisp golden crust with a light, airy centre.",["300 g","Same-day bake","Vegan"]],
["BK201","Plain Butter Croissant","breakfast",85,I.croissant,"Flaky laminated pastry baked until deeply golden.",["1 piece","Pure butter","Vegetarian"]],["BK202","Almond Croissant","breakfast",125,I.croissant,"Butter croissant filled with almond cream and toasted flakes.",["1 piece","Nut filling","Bestseller"]],["BK203","Classic Bagel","breakfast",70,I.bread,"Chewy boiled-and-baked ring, ready for your favourite spread.",["1 piece","Eggless","Sesame top"]],["BK204","Pav & Soft Buns Pack","breakfast",60,I.bread,"Pillowy soft buns for pav bhaji, burgers or breakfast.",["Pack of 6","Eggless","Soft crumb"]],["BK205","Elaichi Milk Rusk","breakfast",90,I.cookie,"Twice-baked crisp rusks gently flavoured with cardamom.",["200 g","Tea-time","Vegetarian"]],
["BK301","Herb Garlic Bread","savory",140,I.savory,"Pull-apart loaf with garlic butter, parsley and herbs.",["Serves 2","Vegetarian","Ready to warm"]],["BK302","Rosemary Focaccia","savory",180,I.savory,"Olive-oil bread topped with rosemary, olives and sea salt.",["300 g","Eggless","Italian style"]],["BK303","Pizza Base Pack","savory",95,I.savory,"Soft hand-stretched bases for quick homemade pizzas.",["Pack of 2","8 inch","Eggless"]],["BK304","Spinach Corn Quiche","savory",135,I.savory,"Buttery tart filled with spinach, sweet corn and cheese custard.",["1 piece","Vegetarian","Contains egg"]],["BK305","Veg Masala Puff","savory",45,I.savory,"Flaky puff pastry with mildly spiced vegetable filling.",["1 piece","Vegetarian","Tea-time"]],["BK306","Chicken Keema Puff","savory",65,I.savory,"Crisp pastry packed with seasoned chicken mince.",["1 piece","Non-veg","Contains egg"]],
["BK401","Cinnamon Swirl Roll","pastries",110,I.pastry,"Soft roll layered with cinnamon sugar and vanilla glaze.",["1 piece","Vegetarian","Soft centre"]],["BK402","Berry Danish","pastries",125,I.pastry,"Flaky Danish with vanilla custard and mixed-berry topping.",["1 piece","Contains egg","Fruit topping"]],["BK403","Chocolate Éclair","pastries",105,I.pastry,"Choux pastry filled with vanilla cream and chocolate glaze.",["1 piece","Chilled","Contains egg"]],["BK404","Vanilla Cream Roll","pastries",75,I.pastry,"Crisp pastry tube filled with light vanilla cream.",["1 piece","Vegetarian","Chilled"]],
["BK501","Classic Glazed Donut","small-treats",65,I.donut,"Soft fried ring finished with a thin vanilla glaze.",["1 piece","Vegetarian","Same-day best"]],["BK502","Chocolate Filled Donut","small-treats",85,I.donut,"Cocoa-glazed donut with a smooth chocolate centre.",["1 piece","Filled","Vegetarian"]],["BK503","Blueberry Muffin","small-treats",90,I.pastry,"Moist vanilla muffin dotted with juicy blueberries.",["1 piece","Contains egg","Fruit bake"]],["BK504","Double Chocolate Muffin","small-treats",95,I.pastry,"Rich cocoa muffin with melting chocolate chips.",["1 piece","Contains egg","Chocolate"]],["BK505","Vanilla Celebration Cupcake","small-treats",75,I.pastry,"Vanilla sponge with silky buttercream and sprinkles.",["1 piece","Eggless available","Party favourite"]],["BK506","French Macaron Box","small-treats",299,I.dessert,"Assorted almond macarons with chocolate and fruit fillings.",["Box of 6","Gluten-free recipe","Contains nuts"]],
["BK601","Butter Cookie Box","cookies",160,I.cookie,"Delicate piped butter cookies with a crisp finish.",["200 g","Vegetarian","Gift-ready"]],["BK602","Chocolate Chip Cookies","cookies",180,I.cookie,"Chewy-centred cookies loaded with dark chocolate chips.",["Pack of 6","Contains egg","Bestseller"]],["BK603","Oatmeal Raisin Cookies","cookies",170,I.cookie,"Wholesome oat cookies with raisins and warm spice.",["Pack of 6","High fibre","Vegetarian"]],["BK604","Almond Biscotti","cookies",190,I.cookie,"Crunchy Italian-style almond biscuits made for dipping.",["200 g","Contains nuts","Eggless"]],
["BK701","Chocolate Truffle Cake","cakes",699,I.cake,"Moist chocolate layers with silky dark chocolate ganache.",["500 g","Serves 5–6","Eggless available"]],["BK702","Classic Black Forest Cake","cakes",649,I.cake,"Chocolate sponge, whipped cream and cherry filling.",["500 g","Serves 5–6","Eggless available"]],["BK703","Red Velvet Cake","cakes",749,I.cake,"Velvety cocoa sponge layered with cream-cheese frosting.",["500 g","Serves 5–6","Premium"]],["BK704","Custom Fondant Cake","cakes",1499,I.cake,"Made-to-order theme cake customised for your celebration.",["Starts at 1 kg","Pre-order 48 hours","Design quote"]],["BK705","Baked New York Cheesecake","cakes",899,I.cake,"Dense, creamy cheesecake over a buttery biscuit base.",["600 g","Serves 6","Chilled"]],["BK706","Rich Fruit Loaf Cake","cakes",420,I.cake,"Fruit-and-nut loaf matured with citrus and warm spices.",["450 g","Contains nuts","Tea cake"]],["BK707","Lemon Tea Cake","cakes",320,I.cake,"Soft buttery loaf brightened with fresh lemon zest.",["400 g","Eggless available","Tea-time"]],
["BK801","Fudge Brownie Box","desserts",260,I.dessert,"Deep chocolate brownies with a crackly top and fudgy centre.",["Box of 4","Contains egg","Best warmed"]],["BK802","White Chocolate Blondies","desserts",280,I.dessert,"Buttery vanilla bars with white chocolate chunks.",["Box of 4","Contains egg","Chewy"]],["BK803","Fresh Fruit Tart","desserts",145,I.dessert,"Crisp tart shell with vanilla custard and seasonal fruit.",["1 piece","Chilled","Seasonal fruit"]],["BK804","Tangy Lemon Bar","desserts",95,I.dessert,"Buttery shortbread topped with a bright lemon custard.",["1 piece","Contains egg","Chilled"]],["BK805","Belgian Chocolate Mousse Cup","desserts",160,I.dessert,"Airy dark chocolate mousse finished with cocoa curls.",["1 cup","Chilled","Gluten-free recipe"]]
];
const products=raw.map(([id,name,category,price,image,description,features])=>({id,name,category,price,image,description,features}));
const cats=[["all","All bakes"],["breads","Breads"],["breakfast","Breakfast & snacks"],["savory","Savory bakes"],["pastries","Pastries & rolls"],["small-treats","Donuts & small treats"],["cookies","Cookies & biscuits"],["cakes","Cakes"],["desserts","Desserts"]],labels=Object.fromEntries(cats),$=id=>document.getElementById(id),state={cat:"all",q:"",sort:"featured",cart:JSON.parse(localStorage.getItem("crumb-cocoa-cart")||"[]")};
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n),save=()=>{localStorage.setItem("crumb-cocoa-cart",JSON.stringify(state.cart));renderCart()};
function filtered(){let x=products.filter(p=>(state.cat==="all"||p.category===state.cat)&&(!state.q||`${p.name} ${p.description} ${p.features.join(" ")}`.toLowerCase().includes(state.q)));if(state.sort==="low")x.sort((a,b)=>a.price-b.price);if(state.sort==="high")x.sort((a,b)=>b.price-a.price);if(state.sort==="name")x.sort((a,b)=>a.name.localeCompare(b.name));return x}
function renderCats(){$("categories").innerHTML=cats.map(([id,n])=>`<button class="${state.cat===id?"active":""}" data-cat="${id}">${n} <small>${id==="all"?products.length:products.filter(p=>p.category===id).length}</small></button>`).join("")}
function renderProducts(){const x=filtered();$("resultCount").textContent=`${x.length} freshly baked choices`;$("products").hidden=!x.length;$("empty").hidden=!!x.length;$("products").innerHTML=x.map(p=>`<article class="product-card"><img src="${p.image}" alt="${p.name}" loading="lazy"><div class="product-body"><span class="tag">${labels[p.category]}</span><h3>${p.name}</h3><p>${p.description}</p><div class="chips">${p.features.map(f=>`<span>${f}</span>`).join("")}</div><div class="card-bottom"><div class="price"><b>${money(p.price)}</b><small>${p.name.includes("Custom")?"starting price":"per pack/item"}</small></div><button class="add" data-view="${p.id}">View &amp; add</button></div></div></article>`).join("")}
function openDetail(id){const p=products.find(x=>x.id===id);$("detail").innerHTML=`<div class="detail-grid"><img src="${p.image}" alt="${p.name}"><div class="detail-copy"><p class="eyebrow">${labels[p.category]} · ${p.id}</p><h2>${p.name}</h2><p>${p.description}</p><p class="price-big">${money(p.price)} ${p.name.includes("Custom")?"onwards":""}</p><ul>${p.features.map(x=>`<li>${x}</li>`).join("")}</ul><p><b>Freshness note:</b> Best enjoyed on the day of purchase. Store chilled items refrigerated.</p><button class="primary" data-add="${p.id}">Add to basket</button></div></div>`;$("detailDialog").showModal()}
function add(id){const x=state.cart.find(i=>i.id===id);x?x.qty++:state.cart.push({id,qty:1});save();$("detailDialog").close();toast("Added to your bakery basket");openCart()}
function totals(){const subtotal=state.cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0),delivery=$("orderForm")?.fulfilment?.value==="Home delivery"?(subtotal>=499?0:49):0;return{subtotal,delivery,total:subtotal+delivery}}
function renderCart(){const count=state.cart.reduce((s,x)=>s+x.qty,0);$("cartCount").textContent=count;$("cartEmpty").hidden=!!count;$("checkout").hidden=!count;$("cartItems").innerHTML=state.cart.map(i=>{const p=products.find(x=>x.id===i.id);return`<div class="cart-line"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><small>${money(p.price)} each</small><div class="qty"><button data-qty="-1" data-id="${p.id}">−</button><b>${i.qty}</b><button data-qty="1" data-id="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">Remove</button></div>`}).join("");const t=totals();$("subtotal").textContent=money(t.subtotal);$("deliveryFee").textContent=t.delivery?money(t.delivery):"Free";$("total").textContent=money(t.total)}
function openCart(){$("overlay").hidden=false;$("drawer").classList.add("open");$("drawer").setAttribute("aria-hidden","false")}function closeCart(){$("drawer").classList.remove("open");$("drawer").setAttribute("aria-hidden","true");setTimeout(()=>$("overlay").hidden=true,250)}
function qty(id,n){const x=state.cart.find(i=>i.id===id);x.qty+=n;if(x.qty<1)state.cart=state.cart.filter(i=>i.id!==id);save()}
function fulfilment(){const d=$("orderForm").fulfilment.value==="Home delivery";$("deliveryFields").hidden=!d;$("pickupFields").hidden=d;$("orderForm").address.required=d;$("orderForm").pickupDate.required=!d;renderCart()}
function order(e){e.preventDefault();const f=new FormData(e.currentTarget),t=totals(),mode=f.get("fulfilment"),lines=state.cart.map((i,n)=>{const p=products.find(x=>x.id===i.id);return`${n+1}. ${p.name} (${p.id})\n   ${money(p.price)} × ${i.qty} = ${money(p.price*i.qty)}`}).join("\n\n"),details=mode==="Home delivery"?`Delivery address: ${f.get("address")}`:`Pickup date: ${f.get("pickupDate")}\nPickup time: ${f.get("pickupTime")}`;const msg=["Hello Crumb & Cocoa Bakehouse,","","I would like to order:","",lines,"",`Subtotal: ${money(t.subtotal)}`,`Delivery: ${t.delivery?money(t.delivery):"Free"}`,`Total: ${money(t.total)}`,"",`Order type: ${mode}`,`Name: ${f.get("name")}`,`Mobile: ${f.get("phone")}`,details,`Notes: ${f.get("notes")||"None"}`,"","Please confirm availability and order time."].join("\n");window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,"_blank","noopener")}
function toast(x){$("toast").textContent=x;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
$("categories").onclick=e=>{const b=e.target.closest("[data-cat]");if(b){state.cat=b.dataset.cat;renderCats();renderProducts()}};$("products").onclick=e=>{const b=e.target.closest("[data-view]");if(b)openDetail(b.dataset.view)};$("detail").onclick=e=>{const b=e.target.closest("[data-add]");if(b)add(b.dataset.add)};$("search").oninput=e=>{state.q=e.target.value.toLowerCase().trim();renderProducts()};$("sort").onchange=e=>{state.sort=e.target.value;renderProducts()};$("reset").onclick=()=>{state.cat="all";state.q="";$("search").value="";renderCats();renderProducts()};$("openCart").onclick=openCart;$("closeCart").onclick=closeCart;$("overlay").onclick=closeCart;$("closeDetail").onclick=()=>$("detailDialog").close();$("cartItems").onclick=e=>{const q=e.target.closest("[data-qty]"),r=e.target.closest("[data-remove]");if(q)qty(q.dataset.id,+q.dataset.qty);if(r){state.cart=state.cart.filter(i=>i.id!==r.dataset.remove);save()}};$("orderForm").addEventListener("change",e=>{if(e.target.name==="fulfilment")fulfilment()});$("orderForm").onsubmit=order;$("customCake").onclick=()=>openDetail("BK704");$("askBaker").onclick=()=>window.open(`https://wa.me/${WA}?text=${encodeURIComponent("Hi Alpha Web Solutions, I viewed the Crumb & Cocoa bakery demo and want a similar bakery website.")}`,"_blank","noopener");const d=new Date();d.setDate(d.getDate()+1);$("orderForm").pickupDate.min=d.toISOString().split("T")[0];renderCats();renderProducts();renderCart();fulfilment();
})();
