(() => {
  const WA = "919392417891";
  const img = {
    classic:"https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&w=800&q=80",
    sun:"https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80",
    desk:"https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&w=800&q=80",
    fashion:"https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=800&q=80",
    optical:"https://images.unsplash.com/photo-1591076482161-42ce6da69f67?auto=format&fit=crop&w=800&q=80",
    contact:"https://images.unsplash.com/photo-1587053934945-c0cc3c5a19c7?auto=format&fit=crop&w=800&q=80",
    care:"https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=800&q=80",
    kids:"https://images.unsplash.com/photo-1556306535-38febf6782e7?auto=format&fit=crop&w=800&q=80"
  };
  const products = [
    ["VN101","Metro Classic","eyeglasses","men","rectangle",1199,img.classic,"Full-rim acetate frame for dependable everyday wear.",["Lightweight","Medium fit","Prescription-ready"]],
    ["VN102","Willow Round","eyeglasses","women","round",1399,img.optical,"Soft round profile with slim temples and a polished finish.",["Full rim","Small fit","Spring hinges"]],
    ["VN103","AirLite Rimless","eyeglasses","unisex","rimless",2199,img.desk,"Minimal rimless design that keeps your look clean and light.",["Ultra-light","Adjustable pads","Large fit"]],
    ["VN104","Edge Half-Rim","eyeglasses","men","rectangle",1699,img.classic,"Smart half-rim frame suited for office and formal wear.",["Half rim","Metal","Medium fit"]],
    ["VN105","Iris Cat-Eye","eyeglasses","women","cat-eye",1799,img.fashion,"Sculpted cat-eye frame with a confident, elegant silhouette.",["Acetate","Medium fit","Statement style"]],
    ["VN106","Everyday Flex","eyeglasses","unisex","wayfarer",999,img.optical,"Flexible everyday frame with a versatile unisex shape.",["TR90","Flexible","Medium fit"]],
    ["VN201","Coastal Polarized","sunglasses","unisex","wayfarer",1899,img.sun,"Polarized lenses for sharper outdoor comfort and reduced glare.",["Polarized","UV400","Medium fit"]],
    ["VN202","Aero Aviator","sunglasses","men","aviator",1599,img.sun,"Classic metal aviators with gradient UV-protective lenses.",["UV400","Metal","Adjustable pads"]],
    ["VN203","Solara Cat-Eye","sunglasses","women","cat-eye",1699,img.fashion,"Oversized fashion sunglasses with broad sun coverage.",["UV400","Large fit","Gradient lens"]],
    ["VN204","Junior SunShield","sunglasses","kids","round",899,img.kids,"Durable, colourful sunglasses made for active children.",["UV400","Flexible","Ages 5–12"]],
    ["VN301","DriveSafe Rx Sun","prescription-sunglasses","men","rectangle",2499,img.sun,"Prescription-compatible tinted eyewear for daytime driving.",["Rx ready","UV400","Anti-glare option"]],
    ["VN302","Urban Rx Shade","prescription-sunglasses","unisex","wayfarer",2299,img.sun,"Everyday sunglasses designed to accept corrective lenses.",["Rx ready","Tint choices","Medium fit"]],
    ["VN303","Luna Rx Sun","prescription-sunglasses","women","cat-eye",2699,img.fashion,"Stylish prescription-ready sun frame with wide coverage.",["Rx ready","UV400","Premium acetate"]],
    ["VN401","ScreenGuard Pro","computer-glasses","unisex","rectangle",1299,img.desk,"Blue-filter glasses designed for long hours on digital screens.",["Blue filter","Anti-glare","Zero power"]],
    ["VN402","Workday Lite","computer-glasses","men","wayfarer",1499,img.desk,"Lightweight computer eyewear with a comfortable all-day fit.",["Blue filter","TR90","Medium fit"]],
    ["VN403","Pixel Round","computer-glasses","women","round",1399,img.optical,"Contemporary round frame with screen-friendly clear lenses.",["Blue filter","Clear lens","Small fit"]],
    ["VN404","StudyBuddy","computer-glasses","kids","rectangle",999,img.kids,"Flexible blue-light eyewear for online classes and study time.",["Blue filter","Flexible","Ages 7–14"]],
    ["VN501","EasyRead +1.00","reading-glasses","unisex","rectangle",799,img.classic,"Ready reading glasses for menus, books and close-up tasks.",["+1.00 power","Lightweight","With case"]],
    ["VN502","EasyRead +1.50","reading-glasses","unisex","round",799,img.optical,"Comfortable pre-powered readers with a classic round profile.",["+1.50 power","Spring hinges","With case"]],
    ["VN503","EasyRead +2.00","reading-glasses","unisex","wayfarer",849,img.desk,"Sturdy ready readers for stronger near-vision support.",["+2.00 power","Full rim","With case"]],
    ["VN601","Daily Clear 30 Pack","contact-lenses","unisex","rimless",1199,img.contact,"Single-use clear contact lenses for convenient daily wear.",["30 lenses","Daily use","Prescription required"]],
    ["VN602","Monthly Comfort 6 Pack","contact-lenses","unisex","rimless",999,img.contact,"Monthly replacement lenses with a moisture-rich design.",["6 lenses","Monthly use","Prescription required"]],
    ["VN603","Aqua Colour Monthly","contact-lenses","unisex","rimless",799,img.contact,"Cosmetic coloured contacts for a subtle aqua-toned look.",["2 lenses","Monthly use","Professional fitting advised"]],
    ["VN604","Brown Colour Monthly","contact-lenses","unisex","rimless",799,img.contact,"Warm brown cosmetic lenses with a natural-looking pattern.",["2 lenses","Monthly use","Professional fitting advised"]],
    ["VN701","Kids FlexiPop","eyeglasses","kids","round",1099,img.kids,"Flexible, lightweight optical frame designed for daily school wear.",["TR90","Flexible","Ages 5–10"]],
    ["VN702","Teen Active","eyeglasses","kids","rectangle",1299,img.kids,"Secure, sporty frame for teenagers and active routines.",["Impact-resistant","Medium fit","Ages 10–16"]],
    ["VN801","Premium Hard Case","accessories","unisex","rimless",349,img.care,"Protective hard-shell case with a soft inner lining.",["Crush resistant","Soft lining","Universal size"]],
    ["VN802","Lens Care Kit","eye-care","unisex","rimless",299,img.care,"Cleaning spray, microfiber cloth and compact repair tool.",["Alcohol-free","Anti-streak","Travel friendly"]],
    ["VN803","Anti-Fog Lens Wipes","eye-care","unisex","rimless",249,img.care,"Individually packed wipes for quick lens cleaning and fog control.",["20 wipes","Anti-fog","Pocket pack"]],
    ["VN804","Classic Eyewear Chain","accessories","women","rimless",399,img.fashion,"Lightweight metal chain that keeps your glasses close and secure.",["70 cm","Metal","Silicone loops"]],
    ["VN805","Sport Retainer Cord","accessories","unisex","rimless",299,img.care,"Adjustable eyewear retainer for sports, travel and outdoor use.",["Adjustable","Non-slip","Washable"]],
    ["VN806","Contact Lens Travel Kit","eye-care","unisex","rimless",449,img.contact,"Compact mirror case with lens holder, tweezers and applicator.",["Leak resistant","Compact","Reusable"]]
  ].map(([id,name,category,audience,shape,price,image,description,features])=>({id,name,category,audience,shape,price,image,description,features}));

  const categories = [
    ["all","All eyewear","◉"],["eyeglasses","Eyeglasses","👓"],["sunglasses","Sunglasses","☀"],["prescription-sunglasses","Prescription sun","◐"],["computer-glasses","Computer glasses","⌘"],["reading-glasses","Reading glasses","Aa"],["contact-lenses","Contact lenses","○"],["eye-care","Eye care","✦"],["accessories","Accessories","⌁"]
  ];
  const labels = Object.fromEntries(categories.map(([id,label])=>[id,label]));
  const lensOptions = [
    ["Frame only",0],["Zero-power anti-glare",599],["Single-vision prescription",799],["Single-vision + blue filter",1299],["Bifocal prescription",1499],["Progressive prescription",2499]
  ];
  const noLens = new Set(["contact-lenses","eye-care","accessories","sunglasses"]);
  const state = {category:"all",audience:"all",shape:"all",sort:"featured",search:"",cart:JSON.parse(localStorage.getItem("visionnest-cart")||"[]")};
  const $ = id => document.getElementById(id);
  const el = {categories:$("categoryCards"),grid:$("productGrid"),count:$("resultCount"),active:$("activeCategory"),search:$("searchInput"),audience:$("audienceFilter"),shape:$("shapeFilter"),sort:$("sortFilter"),empty:$("emptyState"),overlay:$("overlay"),drawer:$("cartDrawer"),cartCount:$("cartCount"),cartItems:$("cartItems"),cartEmpty:$("cartEmpty"),cartSummary:$("cartSummary"),subtotal:$("subtotal"),lensTotal:$("lensTotal"),grand:$("grandTotal"),dialog:$("productDialog"),detail:$("productDetail"),testDialog:$("testDialog"),toast:$("toast")};
  const money = n => new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
  const save = () => {localStorage.setItem("visionnest-cart",JSON.stringify(state.cart)); renderCart();};

  function renderCategories(){el.categories.innerHTML=categories.map(([id,label,icon])=>`<button class="category-card ${state.category===id?"active":""}" data-category="${id}"><span>${icon}</span><b>${label}</b><small>${id==="all"?products.length:products.filter(p=>p.category===id).length} products</small></button>`).join("");}
  function filtered(){let list=products.filter(p=>(state.category==="all"||p.category===state.category)&&(state.audience==="all"||p.audience===state.audience)&&(state.shape==="all"||p.shape===state.shape)&&(!state.search||`${p.name} ${p.description} ${p.features.join(" ")}`.toLowerCase().includes(state.search)));if(state.sort==="low")list.sort((a,b)=>a.price-b.price);if(state.sort==="high")list.sort((a,b)=>b.price-a.price);if(state.sort==="name")list.sort((a,b)=>a.name.localeCompare(b.name));return list;}
  function renderProducts(){const list=filtered();el.count.textContent=`${list.length} products`;el.active.textContent=state.category==="all"?"Showing all product categories":`Showing: ${labels[state.category]}`;el.empty.hidden=!!list.length;el.grid.hidden=!list.length;el.grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="badge">${labels[p.category]}</span></div><div class="product-body"><div class="product-meta"><span>${p.audience}</span><span>${p.shape}</span></div><h3>${p.name}</h3><p class="product-desc">${p.description}</p><div class="feature-tags">${p.features.slice(0,3).map(f=>`<span>${f}</span>`).join("")}</div><div class="product-bottom"><div class="price"><b>${money(p.price)}</b><small>${noLens.has(p.category)?"per pack/item":"frame price"}</small></div><button class="view-btn" data-view="${p.id}">View & add</button></div></div></article>`).join("");}
  function setCategory(id){state.category=id;renderCategories();renderProducts();document.getElementById("shop").scrollIntoView({behavior:"smooth"});}
  function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const lensSelect=noLens.has(p.category)?`<input type="hidden" id="detailLens" value="Standard product"><p class="option-label">This item does not require a frame-lens upgrade.</p>`:`<label class="option-label" for="detailLens">Choose lens option</label><select id="detailLens">${lensOptions.map(([n,v])=>`<option value="${n}" data-price="${v}">${n}${v?` (+${money(v)})`:""}</option>`).join("")}</select>`;el.detail.innerHTML=`<div class="detail-grid"><img src="${p.image}" alt="${p.name}"><div class="detail-copy"><p class="eyebrow">${labels[p.category]} · ${p.id}</p><h2>${p.name}</h2><p>${p.description}</p><div class="detail-price">${money(p.price)} <small>${noLens.has(p.category)?"":"frame only"}</small></div><div class="detail-specs"><span><b>Collection</b><br>${p.audience}</span><span><b>Shape</b><br>${p.shape}</span>${p.features.map(f=>`<span>${f}</span>`).join("")}</div>${lensSelect}<label class="option-label" for="detailColour">Preferred colour</label><select id="detailColour"><option>As shown</option><option>Black</option><option>Brown / Tortoise</option><option>Blue</option><option>Transparent</option></select><button class="primary-btn add-btn" data-add="${p.id}">Add to bag</button></div></div>`;el.dialog.showModal();}
  function addToCart(id){const p=products.find(x=>x.id===id);const lensEl=$("detailLens");const option=lensEl.value;const lensPrice=lensEl.selectedOptions?.[0]?.dataset.price?Number(lensEl.selectedOptions[0].dataset.price):0;const colour=$("detailColour").value;const key=`${id}|${option}|${colour}`;const found=state.cart.find(x=>x.key===key);if(found)found.qty++;else state.cart.push({key,id,option,lensPrice,colour,qty:1});save();el.dialog.close();showToast(`${p.name} added to your bag`);openCart();}
  function renderCart(){const count=state.cart.reduce((s,x)=>s+x.qty,0);el.cartCount.textContent=count;el.cartEmpty.hidden=!!count;el.cartSummary.hidden=!count;el.cartItems.innerHTML=state.cart.map(item=>{const p=products.find(x=>x.id===item.id);return `<div class="cart-line"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><small>${item.option} · ${item.colour}</small><small>${money(p.price+item.lensPrice)} each</small><div class="qty"><button data-qty="-1" data-key="${item.key}">−</button><b>${item.qty}</b><button data-qty="1" data-key="${item.key}">+</button></div></div><button class="remove" data-remove="${item.key}">Remove</button></div>`}).join("");const productTotal=state.cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);const lensTotal=state.cart.reduce((s,x)=>s+x.lensPrice*x.qty,0);el.subtotal.textContent=money(productTotal);el.lensTotal.textContent=money(lensTotal);el.grand.textContent=money(productTotal+lensTotal);}
  function openCart(){el.overlay.hidden=false;el.drawer.classList.add("open");el.drawer.setAttribute("aria-hidden","false");}
  function closeCart(){el.drawer.classList.remove("open");el.drawer.setAttribute("aria-hidden","true");setTimeout(()=>el.overlay.hidden=true,250);}
  function updateQty(key,change){const item=state.cart.find(x=>x.key===key);if(!item)return;item.qty+=change;if(item.qty<=0)state.cart=state.cart.filter(x=>x.key!==key);save();}
  function sendOrder(){if(!state.cart.length)return;const lines=state.cart.map((item,i)=>{const p=products.find(x=>x.id===item.id);return `${i+1}. ${p.name} (${p.id})\n   ${item.colour} | ${item.option}\n   ${money(p.price+item.lensPrice)} × ${item.qty} = ${money((p.price+item.lensPrice)*item.qty)}`}).join("\n\n");const total=state.cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id).price+x.lensPrice)*x.qty,0);const message=["Hi Alpha Web Solutions,","","I viewed the VisionNest Opticals demo and tested this eyewear order:","",lines,"",`Estimated total: ${money(total)}`,`Prescription: ${$("prescriptionStatus").value}`,"","I am interested in a similar optical-store website. Please share the details."].join("\n");window.open(`https://wa.me/${WA}?text=${encodeURIComponent(message)}`,"_blank","noopener");}
  function openTest(){el.testDialog.showModal();}
  function submitTest(e){e.preventDefault();const d=new FormData(e.currentTarget);const message=`Hi Alpha Web Solutions,\n\nI tested the eye-test booking feature in the VisionNest Opticals demo.\n\nName: ${d.get("name")}\nPhone: ${d.get("phone")}\nPreferred date: ${d.get("date")}\nTime: ${d.get("time")}\n\nI am interested in a similar optical-store website.`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(message)}`,"_blank","noopener");}
  function clearFilters(){state.category="all";state.audience="all";state.shape="all";state.sort="featured";state.search="";el.search.value="";el.audience.value="all";el.shape.value="all";el.sort.value="featured";renderCategories();renderProducts();}
  function showToast(text){el.toast.textContent=text;el.toast.classList.add("show");setTimeout(()=>el.toast.classList.remove("show"),2200);}
  el.categories.addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(b)setCategory(b.dataset.category)});el.grid.addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)openProduct(b.dataset.view)});el.detail.addEventListener("click",e=>{const b=e.target.closest("[data-add]");if(b)addToCart(b.dataset.add)});el.search.addEventListener("input",e=>{state.search=e.target.value.trim().toLowerCase();renderProducts()});el.audience.addEventListener("change",e=>{state.audience=e.target.value;renderProducts()});el.shape.addEventListener("change",e=>{state.shape=e.target.value;renderProducts()});el.sort.addEventListener("change",e=>{state.sort=e.target.value;renderProducts()});el.cartItems.addEventListener("click",e=>{const q=e.target.closest("[data-qty]");const r=e.target.closest("[data-remove]");if(q)updateQty(q.dataset.key,Number(q.dataset.qty));if(r){state.cart=state.cart.filter(x=>x.key!==r.dataset.remove);save()}});$("openCart").onclick=openCart;$("closeCart").onclick=closeCart;el.overlay.onclick=closeCart;$("clearCart").onclick=()=>{state.cart=[];save()};$("sendWhatsApp").onclick=sendOrder;$("closeProduct").onclick=()=>el.dialog.close();$("clearFilters").onclick=clearFilters;["bookTestTop","bookTestHero","bookTestService"].forEach(id=>$(id).onclick=openTest);$("closeTest").onclick=()=>el.testDialog.close();$("testForm").addEventListener("submit",submitTest);[el.dialog,el.testDialog].forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close()}));renderCategories();renderProducts();renderCart();
})();
