const classes=[
['Mon','06:30','Strength Foundations','Arjun Rao','Beginner',6,'🏋️'],['Mon','18:30','Forge HIIT','Meera Nair','Intermediate',4,'⚡'],['Tue','07:00','Power Yoga','Kavya Shah','All levels',9,'🧘'],['Tue','19:00','Boxing Conditioning','Rohan Malik','Intermediate',3,'🥊'],['Wed','06:30','Strength Foundations','Arjun Rao','Beginner',8,'🏋️'],['Wed','18:30','Forge HIIT','Meera Nair','Advanced',5,'⚡'],['Thu','07:00','Mobility Flow','Kavya Shah','All levels',12,'🤸'],['Thu','19:00','Boxing Conditioning','Rohan Malik','Intermediate',7,'🥊'],['Fri','06:30','Full Body Burn','Meera Nair','All levels',4,'🔥'],['Sat','08:00','Weekend Warrior','Arjun Rao','All levels',10,'💪']];
const faqs=[['Can I try the gym before joining?','Yes. A ₹399 day pass includes full gym access, one group class and a locker. Upgrade the same day and we will adjust the pass amount.'],['What is the cancellation policy?','Monthly memberships can be cancelled before the next billing date. Prepaid plans are non-refundable after the 7-day cooling-off period, except where applicable law requires otherwise.'],['Can I freeze my membership?','Performance and Elite members can request a 7–30 day freeze for travel, injury or medical reasons.'],['Do you have parking?','Two-wheeler parking is available in the building. Limited car parking is first-come, with paid parking 100 metres away.'],['Are lockers and showers available?','Separate changing rooms, day-use lockers, hot showers and filtered water are included. Bring your own towel and lock.'],['Is the gym beginner-friendly?','Absolutely. New members receive an induction, movement screening and equipment orientation. Strength Foundations is designed for beginners.'],['What should I bring to class?','Wear comfortable training clothes and clean indoor shoes. Bring a water bottle; yoga mats and class equipment are provided.'],['Is personal training included?','Plans include the consultations listed above. Ongoing one-to-one packages are available after a goal assessment.'],['How are online payments secured?','Production payments use a PCI-compliant hosted gateway such as Razorpay or Stripe over HTTPS. The site never stores full card numbers or CVV.'],['What is the minimum age?','Members must be 16 or older. Ages 16–17 require signed parent or guardian consent and may have restricted hours.']];
const schedule=document.querySelector('#schedule');
function render(day){schedule.innerHTML=classes.filter(c=>c[0]===day).map(c=>`<article class="class-card"><i>${c[6]}</i><div><small>${c[1]}</small><small>${c[4]}</small><h3>${c[2]}</h3><p>with ${c[3]} · ${c[5]} spots left</p></div><button class="book" data-session="${c[0]} ${c[1]} — ${c[2]}">Reserve</button></article>`).join('');bindBooks()}
document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-day]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.day)});
document.querySelector('#faq-list').innerHTML=faqs.map(f=>`<details><summary>${f[0]}<span>+</span></summary><p>${f[1]}</p></details>`).join('');
const modal=document.querySelector('#modal'),content=document.querySelector('#modal-content');
function openModal(html){content.innerHTML=html;modal.hidden=false;document.body.style.overflow='hidden';content.querySelectorAll('form').forEach(f=>f.onsubmit=e=>{e.preventDefault();closeModal();showToast('✓ Demo request received. A live website can email and save this booking automatically.')})}
function closeModal(){modal.hidden=true;document.body.style.overflow=''}document.querySelector('#close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};
function booking(session){openModal(`<p class="eyebrow dark">RESERVATION REQUEST</p><h2>Book your session.</h2><p>We’ll hold your spot and send confirmation to your email.</p><form><label>Session<select><option>${session}</option><option>Free gym tour</option><option>Personal training consultation</option></select></label><div class="row"><label>Full name<input required placeholder="Your name"></label><label>Phone<input required type="tel" placeholder="+91"></label></div><div class="row"><label>Preferred date<input required type="date"></label><label>Preferred time<input required type="time"></label></div><label>Email<input required type="email" placeholder="you@example.com"></label><label class="check"><input required type="checkbox"> I agree to the privacy and booking terms.</label><button class="primary">Request reservation</button></form>`)}
function bindBooks(){document.querySelectorAll('.book').forEach(b=>b.onclick=()=>booking(b.dataset.session))}bindBooks();
document.querySelectorAll('.join').forEach(b=>b.onclick=()=>openModal(`<p class="eyebrow dark">SECURE MEMBERSHIP</p><h2>Join ${b.dataset.plan}.</h2><p>This is a safe demo. A production website hands payment to PCI-compliant Razorpay or Stripe. No card data is requested here.</p><form><label>Full name<input required></label><label>Email<input required type="email"></label><label>Mobile<input required type="tel"></label><label class="check"><input required type="checkbox"> I accept the membership terms and privacy policy.</label><button class="primary">Continue to secure checkout →</button><p class="note">🔒 SSL-ready · Hosted payment · No card storage</p></form>`));
const portal=`<p class="eyebrow dark">MEMBER PORTAL · DEMO</p><h2>Welcome back.</h2><div class="portal-card"><div><span>ACTIVE PLAN</span><b>Performance Quarterly</b><small>Renews 18 November 2026</small></div><button class="outline">Manage plan</button></div><div class="portal-stats"><div><span>NEXT CLASS</span><b>Forge HIIT</b><small>Today · 6:30 PM</small></div><div><span>VISITS THIS MONTH</span><b>11</b><small>3-week streak 🔥</small></div></div><h3>Billing history</h3><div class="bill"><span>18 Aug 2026 · Performance</span><b>₹4,999</b></div><div class="bill"><span>18 May 2026 · Performance</span><b>₹4,999</b></div><p class="note">Illustrative data only. Production requires secure login and server-side controls.</p>`;
const privacy=`<p class="eyebrow dark">PRIVACY POLICY TEMPLATE</p><h2>Your data, handled responsibly.</h2><div class="policy"><p><b>Effective:</b> [DD Month YYYY] · <b>Business:</b> [Legal gym name and address]</p><p><b>Template notice:</b> Obtain legal review before publishing.</p><h3>1. Information collected</h3><p>Name, email, phone, date of birth, emergency contact, membership choices, booking history, fitness goals and voluntary information. Payment data is handled by the gateway; the gym does not store full card numbers or CVV.</p><h3>2. Use of information</h3><p>To manage memberships, bookings and payments, provide safe training, send service updates, prevent fraud, meet legal duties and—with consent—send marketing.</p><h3>3. Sharing</h3><p>Necessary data may be shared with trusted hosting, messaging, booking, analytics and payment providers under safeguards. We do not sell personal data.</p><h3>4. Consent and marketing</h3><p>Marketing is optional and consent can be withdrawn. Transactional membership and safety messages may still be sent.</p><h3>5. Retention and security</h3><p>Data is retained only as needed. Controls may include HTTPS, least-privilege access, backups and provider security tools.</p><h3>6. Your rights</h3><p>Subject to law, you may request access, correction, deletion, restriction or a copy of your data, or object to processing.</p><h3>7. Cookies</h3><p>Essential cookies support login and booking. Optional analytics should run only after consent where required.</p><h3>8. Minors</h3><p>Members under 18 require verified guardian consent.</p><h3>9. Contact</h3><p>[privacy email] · [postal address]. You may contact the appropriate authority.</p><h3>10. Updates</h3><p>The latest effective date will be shown and material changes communicated.</p></div>`;
document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.modal==='portal'?portal:privacy));
const lb=document.querySelector('#lightbox');document.querySelectorAll('.gallery button').forEach(b=>b.onclick=()=>{lb.querySelector('img').src=b.querySelector('img').src;lb.hidden=false});lb.onclick=()=>lb.hidden=true;
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.hidden=false;setTimeout(()=>t.hidden=true,4500)}render('Mon');
